// flow-typed signature: b2f9624f8b97528bbeb8d486936563bc
// flow-typed version: <<STUB>>/zen-observable_v0.8.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zen-observable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zen-observable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zen-observable/extras' {
  declare module.exports: any;
}

declare module 'zen-observable/lib/extras' {
  declare module.exports: any;
}

declare module 'zen-observable/lib/Observable' {
  declare module.exports: any;
}

declare module 'zen-observable/scripts/babel-plugins' {
  declare module.exports: any;
}

declare module 'zen-observable/scripts/build' {
  declare module.exports: any;
}

declare module 'zen-observable/scripts/mocha-require' {
  declare module.exports: any;
}

declare module 'zen-observable/src/extras' {
  declare module.exports: any;
}

declare module 'zen-observable/src/Observable' {
  declare module.exports: any;
}

declare module 'zen-observable/test/concat' {
  declare module.exports: any;
}

declare module 'zen-observable/test/constructor' {
  declare module.exports: any;
}

declare module 'zen-observable/test/extras/combine-latest' {
  declare module.exports: any;
}

declare module 'zen-observable/test/extras/merge' {
  declare module.exports: any;
}

declare module 'zen-observable/test/extras/parse' {
  declare module.exports: any;
}

declare module 'zen-observable/test/extras/zip' {
  declare module.exports: any;
}

declare module 'zen-observable/test/filter' {
  declare module.exports: any;
}

declare module 'zen-observable/test/flat-map' {
  declare module.exports: any;
}

declare module 'zen-observable/test/for-each' {
  declare module.exports: any;
}

declare module 'zen-observable/test/from' {
  declare module.exports: any;
}

declare module 'zen-observable/test/map' {
  declare module.exports: any;
}

declare module 'zen-observable/test/observer-closed' {
  declare module.exports: any;
}

declare module 'zen-observable/test/observer-complete' {
  declare module.exports: any;
}

declare module 'zen-observable/test/observer-error' {
  declare module.exports: any;
}

declare module 'zen-observable/test/observer-next' {
  declare module.exports: any;
}

declare module 'zen-observable/test/of' {
  declare module.exports: any;
}

declare module 'zen-observable/test/properties' {
  declare module.exports: any;
}

declare module 'zen-observable/test/reduce' {
  declare module.exports: any;
}

declare module 'zen-observable/test/setup' {
  declare module.exports: any;
}

declare module 'zen-observable/test/species' {
  declare module.exports: any;
}

declare module 'zen-observable/test/subscribe' {
  declare module.exports: any;
}

declare module 'zen-observable/test/subscription' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zen-observable/extras.js' {
  declare module.exports: $Exports<'zen-observable/extras'>;
}
declare module 'zen-observable/index' {
  declare module.exports: $Exports<'zen-observable'>;
}
declare module 'zen-observable/index.js' {
  declare module.exports: $Exports<'zen-observable'>;
}
declare module 'zen-observable/lib/extras.js' {
  declare module.exports: $Exports<'zen-observable/lib/extras'>;
}
declare module 'zen-observable/lib/Observable.js' {
  declare module.exports: $Exports<'zen-observable/lib/Observable'>;
}
declare module 'zen-observable/scripts/babel-plugins.js' {
  declare module.exports: $Exports<'zen-observable/scripts/babel-plugins'>;
}
declare module 'zen-observable/scripts/build.js' {
  declare module.exports: $Exports<'zen-observable/scripts/build'>;
}
declare module 'zen-observable/scripts/mocha-require.js' {
  declare module.exports: $Exports<'zen-observable/scripts/mocha-require'>;
}
declare module 'zen-observable/src/extras.js' {
  declare module.exports: $Exports<'zen-observable/src/extras'>;
}
declare module 'zen-observable/src/Observable.js' {
  declare module.exports: $Exports<'zen-observable/src/Observable'>;
}
declare module 'zen-observable/test/concat.js' {
  declare module.exports: $Exports<'zen-observable/test/concat'>;
}
declare module 'zen-observable/test/constructor.js' {
  declare module.exports: $Exports<'zen-observable/test/constructor'>;
}
declare module 'zen-observable/test/extras/combine-latest.js' {
  declare module.exports: $Exports<'zen-observable/test/extras/combine-latest'>;
}
declare module 'zen-observable/test/extras/merge.js' {
  declare module.exports: $Exports<'zen-observable/test/extras/merge'>;
}
declare module 'zen-observable/test/extras/parse.js' {
  declare module.exports: $Exports<'zen-observable/test/extras/parse'>;
}
declare module 'zen-observable/test/extras/zip.js' {
  declare module.exports: $Exports<'zen-observable/test/extras/zip'>;
}
declare module 'zen-observable/test/filter.js' {
  declare module.exports: $Exports<'zen-observable/test/filter'>;
}
declare module 'zen-observable/test/flat-map.js' {
  declare module.exports: $Exports<'zen-observable/test/flat-map'>;
}
declare module 'zen-observable/test/for-each.js' {
  declare module.exports: $Exports<'zen-observable/test/for-each'>;
}
declare module 'zen-observable/test/from.js' {
  declare module.exports: $Exports<'zen-observable/test/from'>;
}
declare module 'zen-observable/test/map.js' {
  declare module.exports: $Exports<'zen-observable/test/map'>;
}
declare module 'zen-observable/test/observer-closed.js' {
  declare module.exports: $Exports<'zen-observable/test/observer-closed'>;
}
declare module 'zen-observable/test/observer-complete.js' {
  declare module.exports: $Exports<'zen-observable/test/observer-complete'>;
}
declare module 'zen-observable/test/observer-error.js' {
  declare module.exports: $Exports<'zen-observable/test/observer-error'>;
}
declare module 'zen-observable/test/observer-next.js' {
  declare module.exports: $Exports<'zen-observable/test/observer-next'>;
}
declare module 'zen-observable/test/of.js' {
  declare module.exports: $Exports<'zen-observable/test/of'>;
}
declare module 'zen-observable/test/properties.js' {
  declare module.exports: $Exports<'zen-observable/test/properties'>;
}
declare module 'zen-observable/test/reduce.js' {
  declare module.exports: $Exports<'zen-observable/test/reduce'>;
}
declare module 'zen-observable/test/setup.js' {
  declare module.exports: $Exports<'zen-observable/test/setup'>;
}
declare module 'zen-observable/test/species.js' {
  declare module.exports: $Exports<'zen-observable/test/species'>;
}
declare module 'zen-observable/test/subscribe.js' {
  declare module.exports: $Exports<'zen-observable/test/subscribe'>;
}
declare module 'zen-observable/test/subscription.js' {
  declare module.exports: $Exports<'zen-observable/test/subscription'>;
}
