version: 2.1

aliases:
  deploy_branch_only: &deploy_branch_only
    filters:
      branches:
        only:
          - ts-docz

  node: &node
    working_directory: ~/repo
    docker:
      - image: circleci/node:dubnium

  repo_cache_key: &repo_cache_key v1-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}

  restore_repo_cache: &restore_repo_cache
    restore_cache:
      keys:
        - *repo_cache_key

  save_repo_cache: &save_repo_cache
    save_cache:
      key: *repo_cache_key
      paths:
        - ~/repo

  yarn_cache_key: &yarn_cache_key v1-yarn-{{ checksum "yarn.lock" }}

  restore_yarn_cache: &restore_yarn_cache
    restore_cache:
      keys:
        - *yarn_cache_key

  save_yarn_cache: &save_yarn_cache
    save_cache:
      key: *yarn_cache_key
      paths:
        - ~/.cache/yarn
        - node_modules

  static_files_cache_key: &static_files_cache_key v1-build-{{ .Environment.CIRCLE_SHA1 }}

  restore_static_files_cache: &restore_static_files_cache
    restore_cache:
      keys:
        - *static_files_cache_key

  save_static_files_cache: &save_static_files_cache
    save_cache:
      key: *static_files_cache_key
      paths:
        - .docz

  config_npm_registry: &config_npm_registry
    name: Configure private NPM registry auth
    command: |
      echo "always-auth=true" >> ~/.npmrc
      echo "registry=http://npmregistry.hzdg.com/" >> ~/.npmrc
      echo "//npmregistry.hzdg.com/:_authToken=\"$NPM_TOKEN\"" >> ~/.npmrc

  install_node_dependencies: &install_node_dependencies
    name: Install Node dependencies
    command: |
      yarn install --cache-folder ~/.cache/yarn

  build_static_files: &build_static_files
    name: Build Static files
    command: |
      ./node_modules/.bin/docz build

  deploy_docz: &deploy_docz
    command: |
      ./node_modules/.bin/netlify deploy --prod --dir=.docz/dist

jobs:
  checkout:
    <<: *node
    steps:
      - *restore_repo_cache
      - checkout
      - *save_repo_cache

  install:
    <<: *node
    steps:
      - *restore_repo_cache
      - *restore_yarn_cache
      - run: *config_npm_registry
      - run: *install_node_dependencies
      - *save_yarn_cache

  build:
    <<: *node
    steps:
      - *restore_repo_cache
      - *restore_yarn_cache
      - run: *build_static_files
      - *save_static_files_cache

  deploy:
    <<: *node
    steps:
      - *restore_repo_cache
      - *restore_yarn_cache
      - *restore_static_files_cache
      - run: *deploy_docz

workflows:
  build_deploy:
    jobs:
      - checkout:
          <<: *deploy_branch_only
      - install:
          <<: *deploy_branch_only
          context: org-global
          requires:
            - checkout
      - build:
          <<: *deploy_branch_only
          requires:
            - install
      - deploy:
          <<: *deploy_branch_only
          context: org-global
          requires:
            - build
